<!-- Contains required properties for osu!framework projects. -->
<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ApplicationManifest>$(MSBuildThisFileDirectory)app.manifest</ApplicationManifest>

    <!-- Stabilises hot reload, see: https://platform.uno/docs/articles/studio/Hot%20Reload/hot-reload-overview.html?tabs=vswin%2Cwindows%2Cskia-desktop%2Ccommon-issues -->
    <GenerateAssemblyInfo Condition="'$(Configuration)'=='Debug'">false</GenerateAssemblyInfo>

    <!-- Required due to the above -->
    <NoWarn Condition="'$(Configuration)'=='Debug'">$(NoWarn);CA1416</NoWarn>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>

    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)/.build/obj/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)/.build/bin/</BaseOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <Product>osu-sp</Product>
    <Version>0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)osu.licenseheader" Link="osu.licenseheader" />

    <EmbeddedResource Include="Resources/**/*.*" />

    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)CodeAnalysis/BannedSymbols.txt" />

    <!-- Rider compatibility: .globalconfig needs to be explicitly referenced instead of using the global file name. -->
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory)CodeAnalysis/osu.globalconfig" />
  </ItemGroup>

  <PropertyGroup>
    <AnalysisMode>Default</AnalysisMode>
    <AnalysisModeDesign>Default</AnalysisModeDesign>
    <AnalysisModeDocumentation>Recommended</AnalysisModeDocumentation>
    <AnalysisModeGlobalization>Recommended</AnalysisModeGlobalization>
    <AnalysisModeInteroperability>Recommended</AnalysisModeInteroperability>
    <AnalysisModeMaintainability>Recommended</AnalysisModeMaintainability>
    <AnalysisModeNaming>Default</AnalysisModeNaming>
    <AnalysisModePerformance>Minimum</AnalysisModePerformance>
    <AnalysisModeReliability>Recommended</AnalysisModeReliability>
    <AnalysisModeSecurity>Default</AnalysisModeSecurity>
    <AnalysisModeUsage>Default</AnalysisModeUsage>
  </PropertyGroup>
</Project>
